### ISSUE TITLE
DM setup failure, notes needed 

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#10]
Hey @jbkalmbach the tests currently fail for me, see below - apparently I need a stack module called `daf.persistence`, but I have never needed that before. Do I need to "setup" something? Happy to edit the README once I am up and running!

```
bash-3.2$ nosetests .
E
======================================================================
ERROR: Failure: ImportError (No module named daf.persistence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pjm/lsst/DarwinX86/anaconda/2.2.0/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/pjm/lsst/DarwinX86/anaconda/2.2.0/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/pjm/lsst/DarwinX86/anaconda/2.2.0/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/pjm/work/stronglensing/LSST/DESC/Monitor/tests/test_Monitor.py", line 7, in <module>
    import desc.monitor
  File "/Users/pjm/work/stronglensing/LSST/DESC/Monitor/python/desc/monitor/__init__.py", line 1, in <module>
    from monitor import *
  File "/Users/pjm/work/stronglensing/LSST/DESC/Monitor/python/desc/monitor/monitor.py", line 7, in <module>
    import lsst.daf.persistence as dp
ImportError: No module named daf.persistence

----------------------------------------------------------------------
Ran 1 test in 0.035s

FAILED (errors=1)
```

**Comment by drphilmarshall** [comment]
Likewise for `utils`:

```
File "/Users/pjm/work/stronglensing/LSST/DESC/Monitor/python/desc/monitor/monitor.py", line 14, in <module>
    from lsst.utils import getPackageDir
ImportError: No module named utils
```

**Comment by jchiang87** [comment]
@drphilmarshall Do you have the stack installed including lsst_sims?  If you have the stack installed via [these instructions](http://developer.lsst.io/en/latest/build-ci/lsstsw.html), then you would do

```
$ export LSSTSW=<where you've set it up>
$ export EUPS_PATH=$LSSTSW/stack
$ . $LSSTSW/bin/setup.sh
```

Then do

```
$ setup lsst_sims
```

If it complains about not finding an "acceptable version" of lsst_sims, you can do something like

```
$ eups list lsst_sims
   master-ga3712cd25b+17    b1936
$ setup lsst_sims -t b1936
```

**Comment by drphilmarshall** [comment]
Thanks Jim. I tried that, and get this:

```
bash-3.2$ source ~/lsst/loadLSST.bash 
bash-3.2$ setup lsst_sims
Unable to find an acceptable version of lsst_sims
bash-3.2$ eups list lsst_sims
eups list: Unable to find product lsst_sims
```

Then I tried setting up my c-shell, in the same way as we did for `Primes`, but got the same result. I guess my stack is not installed properly. Sigh - I'll go and look up getting the sims stuff in.

**Comment by drphilmarshall** [comment]
`eups distrib install lsst_sims -t sims`
and it's bedtime :-)

**Comment by jchiang87** [comment]
yes, indeed.

**Comment by jbkalmbach** [comment]
Sorry about that @drphilmarshall. That was from when I was trying to use the butler, but since (for now) we are not going that route we don't need it so I removed it in the latest commit.

**Comment by jbkalmbach** [comment]
Whoops. You will need utils though so hopefully you got that to install?

**Comment by drphilmarshall** [comment]
Not yet: right now the stack is helping me improve my development environment more generally ;-)

**Comment by drphilmarshall** [comment]
Update: I needed to install Xcode, for one of the db dependencies. That took a while. Also I needed to `brew install cmake` for one of the other ones. Now grinding back through the list with `eups distrib install lsst_sims -t sims`.

**Comment by drphilmarshall** [comment]
Now hitting boost python problems:

```
[ 33/72 ]  GalSim 1.2.lsst2-1-g6f8a81a+22 ...
...
Unable to build a python loadable module with Boost.Python
```

This is documented at https://github.com/GalSim-developers/GalSim/blob/releases/1.3/INSTALL.md - but I don't understand: why would the LSST DM stack install boost in a way that was _not_ compatible with `GalSim`? Let me know if you have come across this before, otherwise I'll raise it on community.lsst.org

**Comment by cwwalter** [comment]
Phil... if you are doing this on your mac you should just use the anaconda lsst install.  Then you can do a  
conda install lsst-sims

**Comment by rbiswas4** [comment]
I think @danielsf @cwwalter  know all about this.  

I have a quick suggestion: Have you tried a conda install (that is much faster, but I am not sure if it circumvents this issue)

**Comment by drphilmarshall** [comment]
What's the advice for someone who has a partial installation from the
install shel script? Do I just `\rm -rf lsst` and start from scratch with
conda?

**Comment by rbiswas4** [comment]
> Do I just `\rm -rf lsst` and start from scratch with conda?

I think this is the safest since we will know what you have installed. The good thing is that this is much faster than the `eups distrib install` path, so you should probably feel less about the loss of time.

**Comment by drphilmarshall** [comment]
Alright Rahul, I trust you! Nuking lsst now.

**Comment by drphilmarshall** [comment]
Interesting. I accidentally `conda install`-ed `lsst-sims` before `lsst-distrib`, and was told (among other things) that:

```
The following packages will be DOWNGRADED:

    lsst-astrometry-net:        0.50.2.post3-0     --> 0.50.1.post11-1 
    lsst-astrometry-net-data:   0.10.0.post59-1    --> 0.10.0.post41-1 
    lsst-boost:                 1.59.5-3           --> 1.59.1-0        
    lsst-cfitsio:               3360.4-3           --> 3360.3-0        
    lsst-doxygen:               1.8.5.1-2          --> 1.8.5-4         
    lsst-eigen:                 3.2.5-4            --> 3.2.0-4         
    lsst-fftw:                  3.3.4.2-2          --> 3.3.4.1-0       
    lsst-gsl:                   1.16.3-2           --> 1.16.2-0        
    lsst-minuit2:               5.28.00.2-2        --> 5.28.00.1-0     
    lsst-mysqlclient:           5.1.73.3-2         --> 5.1.73.2-0      
    lsst-mysqlpython:           1.2.3.1.post1-2    --> 1.2.3.1-0       
    lsst-pyfits:                3.2.4.2.post1-2    --> 3.2.4.1.post3-1 
    lsst-wcslib:                4.14.2.1-0aaa046_0 --> 4.14.1.post3-0  
    matplotlib:                 1.5.1-np110py27_0  --> 1.4.3-np19py27_3
    numpy:                      1.10.4-py27_0      --> 1.9.0-py27_0    
    python:                     2.7.11-0           --> 2.7.10-2
```

Shouldn't the stack and the sims tools be on the same page? Does it matter which one you install first?

**Comment by rbiswas4** [comment]
> Shouldn't the stack and the sims tools be on the same page?

Not entirely sure, a question for @danielsf . I think the two are maintained at slightly different frequencies
Also the GalSim issue has meant more trouble, the latest sims conda distribution is lsst_sims 2.2.1 or something like that.  

So, while they should be, I don't think they are.

**Comment by drphilmarshall** [comment]
I see - thanks @rbiswas4. The conda advice was good - I am almost set up now. I added my notes as [INSTALL.md](), see what you think. The only thing not working now is the `setup` command - I can `source eups_setups.csh` with no problems, but:

```
pjm@PPA-PC92478 > setup -T v11_0 obs_lsstSim --keep
/opt/anaconda1anaconda2anaconda3/opt/eups/bin/eups_setup: Command not found.
```

Any ideas?

Meanwhile, the Monitor's tests fail for `scipy` reasons:

```
pjm@PPA-PC92478 > nosetests
RuntimeError: module compiled against API version a but this version of numpy is 9
E
======================================================================
ERROR: Failure: ImportError (numpy.core.multiarray failed to import)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pjm/miniconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/pjm/miniconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/pjm/miniconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/pjm/work/stronglensing/LSST/DESC/Monitor/tests/test_Monitor.py", line 7, in <module>
    import desc.monitor
  File "/Users/pjm/work/stronglensing/LSST/DESC/Monitor/python/desc/monitor/__init__.py", line 1, in <module>
    from monitor import *
  File "/Users/pjm/work/stronglensing/LSST/DESC/Monitor/python/desc/monitor/monitor.py", line 11, in <module>
    import sncosmo
  File "/Users/pjm/miniconda2/lib/python2.7/site-packages/sncosmo/__init__.py", line 156, in <module>
    from .dustmap import *
  File "/Users/pjm/miniconda2/lib/python2.7/site-packages/sncosmo/dustmap.py", line 7, in <module>
    from scipy.ndimage import map_coordinates
  File "/Users/pjm/miniconda2/lib/python2.7/site-packages/scipy/ndimage/__init__.py", line 161, in <module>
    from .filters import *
  File "/Users/pjm/miniconda2/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 36, in <module>
    from . import _nd_image
ImportError: numpy.core.multiarray failed to import

----------------------------------------------------------------------
Ran 1 test in 0.852s

FAILED (errors=1)
```

Looks like `sncosmo` is trying to use `scipy.ndimage` but failing. So, I'm `conda install`-ing `scipy`. I don't actually know when I am supposed to use `conda` and when `pip` - how do you find out?

**Comment by drphilmarshall** [comment]
OK good, the `scipy` install worked. Now I get a bona fide LSST error from the Monitor's tests:

```
  File "/Users/pjm/work/stronglensing/LSST/DESC/Monitor/python/desc/monitor/monitor.py", line 15, in <module>
    from lsst.utils import getPackageDir
ImportError: No module named lsst.utils
```

So I guess I need to use "setup" to get this LSST package on my path, but again, 

```
setup -T v11_0 obs_lsstSim --keep
```

fails, with error

```
pjm@PPA-PC92478 > setup -T v11_0 obs_lsstSim --keep
/opt/anaconda1anaconda2anaconda3/opt/eups/bin/eups_setup: Command not found.
```

What `setup` lines should I be using? And do you have any idea why my `$EUPS_DIR` has been set to such a nonsensical name? `INSTALL.md` is up to date with my notes.

**Comment by jchiang87** [comment]
Is it possible to get a more recent version of the Stack than v11_0 using the conda installs?  Maybe it's not an issue for the Mac, but on linux using the conda distribution of v11_0, I ran into serious problems running the assembleCoadd.py step in the Twinkles cookbook.  There's an exchange I had with Simon on this in the Twinkles hipchat room on Nov 30.

**Comment by cwwalter** [comment]
Phil look for other environment variables you have have set.  The you should just need to (csh style)

 # For Anaconda
set path = (/Users/Walter/LSST/Anaconda/bin $path)

 # For DM
source /Users/walter/LSST/Anaconda/bin/eups-setups.csh 

Then, I suspect your issue may be asking for a specific version.  @danielsf and Mario (can't find GH account!) set up the repo to have the "latest" weekly DM snapshot.

So, try starting from a new session and then doing the setup without the tag and see if it works.

 (**edited to say without instead of with and take out unintended markdown markup**)

**Comment by cwwalter** [comment]
arghh **without** the tag.

**Comment by danielsf** [comment]
Note: the LSST conda build is currently incompatible with git lfs, which means the conda install of the stack is not going to move past version sims_2.2.1 for at least a few weeks (the person in charge of fixing the incompatibility has a lot on his plate at the moment).

**Comment by danielsf** [comment]
@jchiang87 What channel are you trying to get your conda build from?

**Comment by danielsf** [comment]
@drphilmarshall What system were you trying to eups distrib install lsst_sims onto?  OSX or Linux?  If OSX, was it El Capitan or Yosemite?

**Comment by drphilmarshall** [comment]
@danielsf El Capitan - but I'm past all that `eups distrib` stuff now!

@cwwalter Thanks, but it seems that `eups_setup.csh` is doing something wrong. I set my PATH as you advised and then tried the `setup` command without the tag (after the `-T` I guess?) and got this:

```
pjm@PPA-PC92478 > source /Users/pjm/miniconda2/bin/eups-setups.csh 
pjm@PPA-PC92478 > setup obs_lsstSim
/opt/anaconda1anaconda2anaconda3/opt/eups/bin/eups_setup: Command not found.
```

The fix was to first

```
unsetenv EUPS_DIR
unsetenv EUPS_PATH
```

The `eups_setups.csh` script was mangling my existing paths and forming junk values for these two variables. The Monitor tests now run fine:

```
pjm@PPA-PC92478 > source setup/setup.csh 
pjm@PPA-PC92478 > nosetests
..
----------------------------------------------------------------------
Ran 2 tests in 14.507s

OK
```

I will finalize the INSTALL notes and close this out. Thanks all!

**Comment by danielsf** [comment]
Just so there's a record of it: El Capitan's SIP (System Integrity Protection) makes it impossible to automatically install GalSim with eups (we were relying on the DYLD_FALLBACK_LIBRARY_PATH environment variable, which is now verboten).  The best fix I can think of is: after anaconda is installed, but before eups distrib installing any LSST software, run the install_name_tool fix on anaconda's libpython2.7.dylib as described here

https://github.com/GalSim-developers/GalSim/wiki/Building-GalSim-with-the-LSST-stack

**Comment by cwwalter** [comment]
I think we decided it is OK as long as it is built ons OSX < El Capitan system.

I am using it on my El Capitan system.

**Comment by jchiang87** [comment]
> @jchiang87 What channel are you trying to get your conda build from?

Sorry, @danielsf, I didn't do the installation. I'll ask the person who did the install.

**Comment by cwwalter** [comment]
@jchiang87 if you look in .condarc you can see what it is.  For example mine:

channels:
- http://eupsforge.net/conda/dev
- defaults

**Comment by jchiang87** [comment]
Thanks @cwwalter.  I don't see .condarc anywhere near where the installation was done (I don't have one in my home directory.)  I've asked Heather, who did the installation.

**Comment by danielsf** [comment]
What output do you get from

```
conda info
```

**Comment by jchiang87** [comment]
```
bash-4.1$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.5.3
     root environment : /nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/anaconda/2.3.0  (writable)
  default environment : /nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/anaconda/2.3.0
     envs directories : /nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/anaconda/2.3.0/envs
        package cache : /nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/anaconda/2.3.0/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

bash-4.1$ 
```

**Comment by jchiang87** [comment]
> Is it possible to get a more recent version of the Stack than v11_0 using the conda installs? Maybe it's not an issue for the Mac, but on linux using the conda distribution of v11_0, I ran into serious problems running the assembleCoadd.py step in the Twinkles cookbook. There's an exchange I had with Simon on this in the Twinkles hipchat room on Nov 30. 

@danielsf  It turns out that the v11_0 version of the Stack that had memory issues running `assembleCoadd.py` here at slac was not a conda installation.   It was built from source.   Sorry for the noise here.
