### ISSUE TITLE
License information in source files, README etc

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#11]
Hey @brianv0 - check out our poster child DESC code project! We used @jchiang87 's template repo, and @jbkalmbach is working on the python source files. Would you mind please looking through these and adding appropriate licence notes to each one, in the recommended locations and formats? The README might need improving as well. If you can give us a good example here, we'll follow it forever. Thanks! :-)

**Comment by brianv0** [comment]
I created pull request #13. It's short and sweet. It refers to the top-level LICENSE file, but we could modify that to point to a file at lsst-desc.org/LICENSE.txt or something similar.

**Comment by drphilmarshall** [comment]
Fixed in 6950f0a86c7ff386f89f861edf14b0cf5f1044d2 by @brianv0 ! :-)
