### ISSUE TITLE
Module structure

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#2]
@jchiang87

Hi Jim - Would you mind doing the necessary things to set this repo up so it can be summoned via

``` python
import desc.monitor
```

please? I'd like to see how this is done - normally I would put an `__init__.py` in `monitor` and insert statements like `from source.py import *`, so that I can then simply `import monitor`. But in https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/105 you recommended renaming the `monitor` folder to `python` - so we might need some guidance in the `README` after you've done some moving and editing. Thanks!

**Comment by jchiang87** [comment]
sure, I'll give it a go, but once we settle on a real package management system, what I implement will need to change somewhat.

**Comment by drphilmarshall** [comment]
Yep, no worries. We officially love refactoring! Thanks Jim. BTW this is
pathfinder Level 3 code, so we should follow DM standards as well as module
structure - great if you can point out any instances where you do things in
particular ways because of DM.

**Comment by jchiang87** [comment]
I created a branch `issues/2/package_reorg` (I guess DM would have called it `tickets/DM-<JIRA issue number>`) with my proposed changes.  I've updated the README, but here's a demo nonetheless:

```
bash-4.1$ git clone git@github.com:DarkEnergyScienceCollaboration/Monitor.git
bash-4.1$ cd Monitor
bash-4.1$ git checkout issues/2/package_reorg
Branch issues/2/package_reorg set up to track remote branch issues/2/package_reorg from origin.
Switched to a new branch 'issues/2/package_reorg'
bash-4.1$ source setup/setup.sh 
bash-4.1$ python tests/test_Monitor.py 
No IO enabled yet.
.No IO enabled yet.
No algorithms coded yet.
.
----------------------------------------------------------------------
Ran 2 tests in 0.017s

OK
bash-4.1$ ipython
Python 2.7.2 (default, Oct 17 2012, 03:00:49) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import desc.monitor

In [2]: my_monitor_obj = desc.monitor.Monitor()

In [3]: 
```

I took the liberty of add a `tests` folder and a stub of some unit testing code.

If we were following DM conventions, I would run continuous integration testing, then ask for code review, and then merge into master or submit a pull-request to do so.

**Comment by drphilmarshall** [comment]
Excellent! Thanks Jim. Well, let's do this DM-style, then - with one
wrinkle. With GitHub it's good to start the PR first, because it's the PR
thread that lays out all the commits so we can review them. Also, I think
it'll be easy to set up Travis CI once the PR is open - let's see if we can
make that work. See you on the PR thread in a minute!

**Comment by drphilmarshall** [comment]
Nailed in #5
