### ISSUE TITLE
Update monitor code to interact with SQL database

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Monitor#24]

**Comment by jbkalmbach** [comment]
This will interact with NERSC database setup by @jchiang87, but will require ssh tunneling and db-auth setup that will be documented.

**Comment by jchiang87** [comment]
@jbkalmbach I've got some fixes for the .travis.yml file that I expect will fix the build problems on this branch.  I'll push them to master so you can merge them here.

**Comment by jbkalmbach** [comment]
That'd be great. Thanks!

**Comment by jchiang87** [comment]
ok, it's done (ad61a765c).  I added the pylint --py3k and coverage tests as well.

**Comment by jchiang87** [comment]
Hey @jbkalmbach:  I'd like to start using this code at NERSC, and it looks close to merging into master, but I have a feature request, i.e., making the db info [here](https://github.com/DarkEnergyScienceCollaboration/Monitor/blob/88ac99bc5bf7dcf2eefc9059176c27a5ab4b8476/python/desc/monitor/dbConnection.py#L8) settable by the user at runtime.  Could you open a PR where we can discuss the options for that?  Thanks!

**Comment by rbiswas4** [comment]
Hi @jbkalmbach, I made some changes to get the travis tests on python 3 compatibility to pass. The main problem was an example.py file that had stayed from before. I went through the code and it seems fine. However, should we not have docstrings and examples as well as unit tests for this code?

**Comment by jbkalmbach** [comment]
I'll add that as an issue to the epic. Let's close this out and let other people try it out. Thanks for looking at the code.

**Comment by rbiswas4** [comment]
ok
