### ISSUE TITLE
Compute nightly fluxes and uncertainties

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#51]
So far we have restricted the Twinkles light curves to one visit per filter per night - but in Run 3 we will get the full DDF stream, with multiple visits per night. The rough DM plan for the DDFs seems to be "do the same as we do in WFD, wherever possible" which means that we will probably just run the same Level 2 pipeline that we already developed, and so produce a ForcedSource for every visit, and ~10 per night. I think this means we need the Monitor to be able to compute _nightly fluxes_ by combining the measurements taken in different visits during the same night. Comments welcome, SN afficionados! @rbiswas4 @wmwv 

Can the Monitor write new tables to the Pserv database, @jchiang87 ? This would save us having to sum the same fluxes over and over again. Lets postpone implementing this until we've seen how fast it is to combine fluxes on the fly, though.

**Comment by cdfassnacht** [comment]
@drphilmarshall - I'm not at all convinced that this is something that we want to do.  By binning, which combining measurements to get a nightly flux effectively does, we are throwing away information.  I have no idea for what kind of stochastic behavior SN exhibit on these kind of time scales, but I could imagine that AGN might have short time-scale variations, which may be useful information in time-delay measurements.

**Comment by drphilmarshall** [comment]
Good point: the CatSim AGN do not have short timescale variations, but the real ones may well do. Let's not bin the SL light curves then, on principle. This could be an SN-only use case.

**Comment by rbiswas4** [comment]
While SNIa do not have features on this time-scale, (and so co-addition) is safe, I too prefer to not coadd the nightly fluxes, unless DM plans to treat them that way (as far as I know this is not the case). We should simulate the expected behavior as far as possible.

**Comment by wmwv** [comment]
There's nothing particular to be gained by thinking too hard about binning points on the same night.  I would recommend just taking the lightcurves as we get them.

**Comment by rbiswas4** [comment]
So, all votes for not expanding monitor capability along these lines. @drphilmarshall did you have some necessity in mind that we are missing?

**Comment by drphilmarshall** [comment]
Nope! If we're all OK with working with visit fluxes rathre than nightly
fluxes, we can just close this out :-)
