### ISSUE TITLE
LightCurve class

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#7]
@jbkalmbach 

I propose we make a `LightCurve` class as the centerpiece of the Monitor code. We'll want to be able to do things like this:

``` python
import desc.monitor
Object = 2341626719828
we = desc.monitor.LightCurve()
we.build_lightcurve(of=Object)
we.visualize_lightcurve(with='interaction')
```

See #6 for thoughts on light curve visualization! :-)
I think this class is the key component of the Simplest Possible Implementation #1

**Comment by jchiang87** [comment]
Hi Guys,

In case you haven't seen it, @SimonKrughoff has some code that extracts the light curve fluxes by `objectId` from the `forced_src` catalogs [here](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/plot_point_mags_gri.py) using the data butler, etc..

**Comment by drphilmarshall** [comment]
Excellent, we'll need that. Thanks @jchiang87 !

Also, let's follow `sncosmo` when working with multi-filter light curve data, to make it easy to do light curve fitting later. It's a pretty light-weight dependency (just `pip install --no-deps sncosmo`. [This page here](http://sncosmo.readthedocs.org/en/v1.2.x/photdata.html) describes what an `sncosmo` multi-filter light curve looks like, and it's pretty much what any of use would have written down first anyway. ( @rbiswas4 I assume you already work with light curve data in `sncosmo` `astropy` tables? ) 

In this model, the job of the v1 Monitor is basically going to be: summon the Butler, have him fetch some ForcedSource data, and then package into an `sncosmo`-style `astropy` Table within a Monitor `LightCurve` class so that we can them plot it and check it against our truth curves. Sound like a plan?

**Comment by rbiswas4** [comment]
Great! @jchiang87 

> Also, let's follow sncosmo when working with multi-filter light curve data, to make it easy to do light curve fitting later. It's a pretty light-weight dependency (just pip install --no-deps sncosmo. This page here describes what an sncosmo multi-filter light curve looks like, and it's pretty much what any of use would have written down first anyway. ( @rbiswas4 I assume you already work with light curve data in sncosmo astropy tables? )

Exactly. I think the sncosmo format is a pretty good one. And adding columns to the tables as we see fit is easy. There are a couple of things I would like to add
1. Depending on how we are doing things, we could either use sncosmo directly, or if we are importing lsst.sims, sncosmo is part of that package. So doing setup sncosmo will set up a recent release version of sncosmo. If we are importing `lsst.sims` as a dependency (and I think we would be) then using the setup version of sncosmo keeps things at the same release. My intent is to regularly update sncosmo to the latest release unless there is a problem, and I am quite careful to do this (unless there is a good reason to not do so) if an important change in sncosmo happens. I have a slight preference for using this mode for the above reason, but am happy with a direct import too.
2.  The only change I would suggest is having this as a `pandas.DataFrame` rather than `astropy.Table`. Interchanging between the two is easy and I do that all the time, but I find a number of pandas features easier and useful to use (This might reflect my ignorance of how to use the astropy features as well). 

Also, I think I have most of what is needed to make the lc class in different projects already and will discuss this more in this issue.

**Comment by jbkalmbach** [comment]
Ok, so a problem with the plan laid out so far is mentioned by @jchiang87 in #4.

> Unfortunately, to use that code with the butler etc., the full output directory structure is probably needed, i.e., some sample forced source catalogs won't be sufficient.

If we want to work with just forced source tables we won't be able to use the butler is how I interpret this. Therefore, we'll need to pull the data out a different way.

**Comment by rbiswas4** [comment]
@SimonKrughoff @drphilmarshall Can we define what inputs we want the light curve class to work on?

Can we say that there will be a piece of code that uses the butler to obtain forced photometry results in the form of 'say' a numpy record array and the LC class will work with this record array ?

**Comment by drphilmarshall** [comment]
Well. I guess the Monitor will need to be able to use the Butler to
assemble LightCurves out of DM data files, but a LightCurve object itself
should be able to be initialized either by the Monitor (which would pass
through whatever the Butler finds it convenient to serve us), _or_ a simple
sncosmo-style data file. This way, the UW group can be working on making
LightCurves plot themselves, and maybe we can make the Butler work for us
here?

We do not want the Monitor to be site-specific though, so if you have
Butlers working up there in Seattle it would be good to try and put them to
work - but we need plotting code and fast so I suggest you give the
`LightCurve.__init__()` some options. Sound good?

**Comment by jchiang87** [comment]
Isn't the end-game for the Monitor code to read the forced source fluxes from the Level 2 db tables?  It sounds like we are sort of heading in that direction.  Maybe the butler-based code should just stuff some Level 2 tables and then have some tools to export data from those tables as numpy arrays or whatever.

BTW, that "butler-based code" would essentially be doing what the Stack's `daf_ingest` package should do, but I don't think it has that capability yet.

**Comment by jbkalmbach** [comment]
So, I took just the tables and didn't use the butler method at all, I just directly got what I needed from them by interacting directly with the fits files. Then I built up a rough draft of the code that works exactly like Phil outlined above. I just pushed it in the commit mentioned above. To see how it works here is a ipython notebook: https://gist.github.com/jbkalmbach/e29af05df20ee6c458a6.

A couple things still need to be worked out especially connecting our phosim input catalogs to this, but I think this is a good starting point at least.

**Comment by jbkalmbach** [comment]
Oh, also the plot doesn't look so great due to the provided test tables. I will bring that up in #4.

**Comment by drphilmarshall** [comment]
Nice! We can refactor to use the Butler later: I see a visualized light
curve and some nice looking OO python calls so yes, I'd say this was a good
starting point :-)  I think you should check in the demo notebook, and link
to it from the README. They make really nice documentation, I think. Later
we'll beed to clear the outputs to save space, but for now showing a light
curve from the test dataset is great!

**Comment by drphilmarshall** [comment]
Installed Monitor, ran tests, initial LightCurve class  looks done.
