### ISSUE TITLE
Coping without warps

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#81]
A move is afoot in the DC2_Repo to trash the warps images after DIA (while keeping the calexps, compressed). Dominique Fouchez asserts that we don't need warps for light curve photometry in [this comment](https://github.com/LSSTDESC/DC2_Repo/issues/52#issuecomment-351747408). Does the Monitor currently use the warp images to make postage stamps? Can we live without warps? I think so, but just wanted to check.

**Comment by rbiswas4** [comment]
But I think we want postage stamps! It may be ok for them to not be made by monitor and supplied by the DM stack, but we need these. These are the inputs to @dannygoldstein 's code for real-artifact analysis, and we want to run things through that.

**Comment by jchiang87** [comment]
You can make postage stamps with the Monitor code from the calexps.  They just won't be registered in a nice way to make a movie.

**Comment by jbkalmbach** [comment]
Yeah, I think the [PostageStampMaker](https://github.com/LSSTDESC/Monitor/blob/master/python/desc/monitor/PostageStampMaker.py) code will be fine to create the input for @dannygoldstein 's code.

**Comment by drphilmarshall** [comment]
OK good - thanks all! Will rest easy.
